export const COMMANDS_FETCH = "command/COMMANDS_FETCH";
export const COMMANDS_FETCH_SUCCEEDED = "command/COMMANDS_FETCH_SUCCEEDED";
export const COMMANDS_FETCH_FAILED = "command/COMMANDS_FETCH_FAILED";